### ISSUE TITLE
Out: env: node: No such file or directory

### ISSUE THREAD

**Issue by aristidesfl** [PixnBits/sublime-text-npm#16]
I get this for example when using the `npm install` command: 

`Out: env: node: No such file or directory`

I'm not having path problems with other extensions.
Using https://github.com/int3h/SublimeFixMacPath

Sublime Text 3 (3066)
OS X 10.10.1

**Comment by PixnBits** [comment]
Thanks for the report, will investigate.

**Comment by PixnBits** [comment]
I'm unable to reproduce. However, I suspect this is a race condition as both plugins write to `os.environ['PATH']`. It is inappropriate for `sublime-text-npm` to do so, so I will make a change that might also fix this.

Is this a standard node & npm installation?

**Comment by aristidesfl** [comment]
yes 
`/usr/local/bin/node`
`/usr/local/bin/npm`

**Comment by PixnBits** [comment]
Oh. That's different than I thought. Of note is (node issue 3911)[https://github.com/joyent/node/issues/3911] which says
```
The node binary is not on your $PATH.
```
Looking at (sublime-text-git)[https://github.com/kemayo/sublime-text-git/blob/master/git.py#L122] and (SublimeFixMacPath)[https://github.com/int3h/SublimeFixMacPath/blob/master/FixPath.py#L24] they both specify `env`. I'm guessing this is the difference (`npm` doesn't have a `$PATH` to `node`) and will fix the issue you're describing (not the one I was distracted with :).

BTW, Are you comfortable `git clone`ing this repo to test a fix?

**Comment by aristidesfl** [comment]
Sure!

**Comment by PixnBits** [comment]
Awesome, thanks! The fix should be in [master](https://github.com/PixnBits/sublime-text-npm/tree/master) as of 463d34d334650a3781817106fa39347695d8b70b. Let me know how it goes!

(FWIW I have this cloned to `/Users/pixnbits/Library/Application Support/Sublime Text 3/Packages/sublime-text-npm/`)

**Comment by aristidesfl** [comment]
It works, thanks!

**Comment by PixnBits** [comment]
Thank you!!

**Comment by PixnBits** [comment]
Released in regular channel in [0.0.8](https://github.com/PixnBits/sublime-text-npm/releases/tag/0.0.8).
There was a merge conflict I resolved in that release so please let me know if you find a regression. Shouldn't, but you know theory vs practice :wink:
