### ISSUE TITLE
Add `npm test` command

### ISSUE THREAD

**Issue by deedubs** [PixnBits/sublime-text-npm#17]
https://www.npmjs.org/doc/cli/npm-test.html

**Comment by PixnBits** [comment]
More pressure for #9 to get done! Thanks for the link, BTW.

**Comment by PixnBits** [comment]
Added in [0.0.8](https://github.com/PixnBits/sublime-text-npm/releases/tag/0.0.8)

**Comment by deedubs** [comment]
Thanks @PixnBits!
