### ISSUE TITLE
How to elevate permissions?

### ISSUE THREAD

**Issue by marshallswain** [PixnBits/sublime-text-npm#23]
Is there a way to overcome the EACCESS errors from not being run with sudo?

**Comment by PixnBits** [comment]
Looks like [Sublime asks for credentials](https://sublimetext.userecho.com/topic/27820-prompt-if-need-elevated-permission-to-save/) when it encounters such an error.
Would such a dialog be user-friendly in your case?
(I haven't encountered this myself, so I don't have a solution as of now :frowning:)

**Comment by marshallswain** [comment]
I'm not sure how you would implement a dialog on this because everything seems to be running just fine until the very end of installing a module, then it gives the error.  Maybe a "run as super user" option could be made available for each of the commands?  I'd even be happy with a workaround.  :)

**Comment by marshallswain** [comment]
Apparently I just needed to restart Sublime Text after installation.  It's working, now.

**Comment by PixnBits** [comment]
Good to know! Thanks for updating! :+1:
