### ISSUE TITLE
analyze package.json to allow `npm run-script <script name>`

### ISSUE THREAD

**Issue by MiningPotatoes** [PixnBits/sublime-text-npm#34]
i have my doc-building script listed as a custom script in the `package.json`. I would really like to be able to run my scripts from sublime.

**Comment by PixnBits** [comment]
Yes! As a temporary, try "run arbitrary"?

**Comment by MiningPotatoes** [comment]
I like it!

**Comment by PixnBits** [comment]
Starting work for this on the [npm_run_script](https://github.com/PixnBits/sublime-text-npm/tree/npm_run_script) branch. Pretty much there minus the long-running bit.

**Comment by PixnBits** [comment]
added in https://github.com/PixnBits/sublime-text-npm/pull/38
I need to tag a new version :)
