### ISSUE TITLE
Pressing <ESC> without selecting a Script to run, runns Task anyway

### ISSUE THREAD

**Issue by tjventurini** [PixnBits/sublime-text-npm#43]
Just used the Plugin for the first time and I just wanted to see if all my scripts (defined in my package.json file) are listed. They did so I simply pressed <ESC> but then the `production` task was excecuted. Glad that it wasent a destroying script that was excecuted.

Here my Tasks from the package.json file:

    {
      "private": true,
      "scripts": {
        "dev": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "hot": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "production": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
      },
      "devDependencies": {
        "axios": "^0.15.2",
        "jquery": "^3.1.0",
        "laravel-mix": "^0.6.0",
        "lodash": "^4.16.2",
        "vue": "^2.0.1",
        "foundation-sites": "^6.3.0"
      }
    }

Would be nice if this would be resolved. Is realy the only think I am missing right now :)

Thanks for the addon anyway! :+1:

**Comment by PixnBits** [comment]
Should be fixed in the latest (v0.0.10) release, please close if so
I need to just make the jump to 1.0.0 and semver this thing :embarrassed:

**Comment by tjventurini** [comment]
Is fixed, thank you :+1:
