### ISSUE TITLE
NPM commands

### ISSUE THREAD

**Issue by Yoruba** [PixnBits/sublime-text-npm#9]
Hello, it would be nice if you could type a NPM command yourself like NPM gulp watch for example.

Create tool, Adri

**Comment by PixnBits** [comment]
Added in [0.0.8](https://github.com/PixnBits/sublime-text-npm/releases/tag/0.0.8)

**Comment by PixnBits** [comment]
Last line of output may be missed. Might need to reopen or open a bug. Investigating.
